'use client';

import Link from 'next/link';
import { BulletList, CardGrid } from '@/components/legal/LegalPageShell';
import { OPEN_CONSENT_SETTINGS_EVENT } from '@/lib/consent';

const dataYouProvide = [
  {
    title: 'Contact form',
    body: 'Your name, email address, and the content of your message.',
  },
  {
    title: 'Reservation requests',
    body: 'Your name, email, phone number, preferred contact method, the selected property, your check-in and check-out dates, and the number of guests.',
  },
  {
    title: 'Event inquiries',
    body: 'Your name, email, phone number, preferred contact method, event type, event date, expected number of guests, and any optional details you share.',
  },
];

const dataCollectedAutomatically = [
  'Pages you view and how you navigate the website',
  'Browser type, device, and operating system',
  'Approximate location derived from your IP address',
  'The website or source that referred you to us',
  'Your interactions with our Meta and Google advertising campaigns when you accept advertising cookies',
];

const howWeUse = [
  'Respond to your inquiries and messages',
  'Process, confirm, and manage your booking and event requests',
  'Contact you through your preferred method about your request',
  'Operate, secure, maintain, and improve the website',
  'Measure advertising effectiveness and create relevant audiences when you consent',
  'Comply with our legal, tax, and accounting obligations',
];

const legalBases = [
  {
    title: 'Performance of a contract',
    body: 'Handling your booking or event request and taking steps at your request before entering into an agreement.',
  },
  {
    title: 'Consent',
    body: 'Loading Google Analytics cookies and the Meta and Google Ads advertising technologies, which we activate only after your explicit choice for each category. You can change or withdraw your consent at any time.',
  },
  {
    title: 'Legitimate interests',
    body: 'Keeping the website secure, understanding how it is used, improving it, and responding to general inquiries.',
  },
  {
    title: 'Legal obligation',
    body: 'Retaining records where required by applicable tax and accounting law.',
  },
];

const processors = [
  {
    title: 'Resend',
    body: 'Delivers the email notifications generated by our contact, reservation, and event forms.',
  },
  {
    title: 'Supabase',
    body: 'Securely stores reservation requests so we can manage and follow up on your booking.',
  },
  {
    title: 'Google Analytics (Google LLC)',
    body: 'Provides aggregated website-usage analytics through cookies and similar technologies.',
  },
  {
    title: 'Google Ads (Google LLC)',
    body: 'Measures the reservations and inquiries generated by our search and display campaigns and builds remarketing audiences. Google acts as an independent controller for parts of this processing under its own advertising terms.',
  },
  {
    title: 'Meta Platforms',
    body: 'Provides the Meta Pixel. Depending on the purpose, Meta may process data on our behalf or act with us as a joint controller for the collection and transfer of Event Data used for advertising targeting and improvement.',
  },
  {
    title: 'Vercel',
    body: 'Hosts the website and processes standard server and security logs.',
  },
];

const dataRetention = [
  'Contact and inquiry messages are kept only as long as needed to handle your request, plus a reasonable follow-up period.',
  'Reservation records are retained for booking administration and to meet legal and accounting requirements.',
  'Analytics data is retained according to our Google Analytics retention settings.',
  'Google Ads conversion and remarketing data is retained for the periods set by Google, and membership of a remarketing list expires after the maximum duration allowed by Google Ads.',
  'Under the Meta Business Tools Terms, Meta may retain Event Data for up to two years and audiences created from it until they are deleted through the account tools.',
];

const gdprRights = [
  'Access the personal data we hold about you',
  'Request correction of inaccurate or incomplete data',
  'Request erasure of your data',
  'Request restriction of, or object to, our processing',
  'Request portability of the data you provided to us',
  'Withdraw consent at any time, without affecting processing carried out beforehand',
  'Lodge a complaint with your local data protection supervisory authority',
];

export default function PrivacyContentEn({
  termsHref,
  cancellationHref,
}: {
  termsHref: string;
  cancellationHref: string;
}) {
  return (
    <>
      <section className="mb-10" data-animate="fade-up" data-delay="1">
        <h2 className="font-head text-3xl font-bold text-black">Who We Are</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <div className="space-y-4 text-black/80 leading-relaxed">
            <p>
              Or Hakerem (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;the company&rdquo;) provides short-term
              luxury accommodation in Tel Aviv and operates the website at orhakerem.com. We are the
              controller responsible for the personal data described in this policy.
            </p>
            <p>
              You can reach us about any privacy matter at{' '}
              <a
                href="mailto:keremliving@gmail.com"
                className="font-semibold text-primary underline underline-offset-4 transition-colors hover:text-primary-light"
              >
                keremliving@gmail.com
              </a>{' '}
              or by post at 35 Hakovshim Street, Tel Aviv, Israel. If you book through Airbnb, that stay
              is also governed by Airbnb&apos;s own privacy policy.
            </p>
          </div>
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up" data-delay="2">
        <h2 className="font-head text-3xl font-bold text-black">Information We Collect</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 space-y-6">
          <div className="rounded-2xl border border-primary/10 bg-cream/50 p-6 md:p-8">
            <h3 className="font-head text-2xl font-semibold text-black">Information you provide</h3>
            <p className="mt-2 text-black/75 leading-relaxed">
              We only receive this information when you choose to send it to us through one of our forms.
            </p>
            <div className="mt-6">
              <CardGrid items={dataYouProvide} />
            </div>
          </div>

          <div className="rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
            <h3 className="font-head text-2xl font-semibold text-black">
              Information collected automatically
            </h3>
            <p className="mt-2 text-black/75 leading-relaxed">
              Depending on your consent choices, our analytics and advertising providers may collect
              limited technical information through cookies and similar technologies:
            </p>
            <div className="mt-5">
              <BulletList items={dataCollectedAutomatically} />
            </div>
          </div>
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up" data-delay="3">
        <h2 className="font-head text-3xl font-bold text-black">Cookies, Analytics &amp; Advertising</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <div className="space-y-4 text-black/80 leading-relaxed">
            <p>
              We use Google Analytics 4 to understand how visitors use the website so we can improve it.
              Google Analytics sets cookies and processes the technical information described above. These
              analytics cookies load only if you separately accept the “Audience measurement” category.
            </p>
            <p>
              With your separate consent for the “Advertising” category, we also use the Meta Pixel. It
              helps us measure actions taken after an interaction with our ads and create relevant
              audiences on Meta services. The Pixel may process technical information, IP address, page
              address, browser identifiers, and campaign information. We do not send form content to Meta
              through the Pixel.
            </p>
            <p>
              The same &ldquo;Advertising&rdquo; consent covers Google Ads. We run search and display
              campaigns, and the Google Ads tag lets us measure the reservations and inquiries that follow
              an ad click and show relevant ads to people who have already visited the site
              (remarketing). Where our Google Analytics property is linked to Google Ads, analytics data
              may also be used to build these audiences. We do not send form content to Google.
            </p>
            <p>
              You can change or withdraw your choice at any time using the button below, refuse or delete
              cookies through your browser settings, opt out of Google Analytics across all websites
              using Google&apos;s{' '}
              <a
                href="https://tools.google.com/dlpage/gaoptout"
                target="_blank"
                rel="noopener noreferrer"
                className="font-semibold text-primary underline underline-offset-4 transition-colors hover:text-primary-light"
              >
                opt-out browser add-on
              </a>
              , turn off personalised advertising in your{' '}
              <a
                href="https://myadcenter.google.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="font-semibold text-primary underline underline-offset-4 transition-colors hover:text-primary-light"
              >
                Google Ad Settings
              </a>
              , or adjust your{' '}
              <a
                href="https://www.facebook.com/settings?tab=ads"
                target="_blank"
                rel="noopener noreferrer"
                className="font-semibold text-primary underline underline-offset-4 transition-colors hover:text-primary-light"
              >
                Meta ad preferences
              </a>
              . Blocking cookies will not affect your ability to browse the site or contact us.
            </p>
          </div>

          <button
            type="button"
            onClick={() => window.dispatchEvent(new Event(OPEN_CONSENT_SETTINGS_EVENT))}
            className="mt-6 inline-flex items-center rounded-full border border-primary/15 bg-white px-5 py-2.5 font-semibold text-primary shadow-sm transition-colors hover:bg-primary/5"
          >
            Manage cookie preferences
          </button>
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">How We Use Your Information</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <BulletList items={howWeUse} />
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">Legal Basis for Processing</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-cream/50 p-6 md:p-8">
          <p className="text-black/75 leading-relaxed">
            Where the EU or UK General Data Protection Regulation applies, we rely on the following legal
            bases:
          </p>
          <div className="mt-6">
            <CardGrid items={legalBases} />
          </div>
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">Sharing &amp; Third-Party Services</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <p className="text-black/80 leading-relaxed">
            We do not sell your personal data. Depending on the service and purpose, third parties
            may process data on our behalf, act as independent controllers, or act jointly with us
            as controllers. For certain Meta Business Tools processing under the GDPR, Or Hakerem
            and Meta Platforms Ireland Limited are joint controllers for collecting and
            transmitting Event Data. More information is available in the{' '}
            <a
              href="https://www.facebook.com/legal/terms/businesstools/preview"
              target="_blank"
              rel="noopener noreferrer"
              className="font-semibold text-primary underline underline-offset-4 transition-colors hover:text-primary-light"
            >
              Meta Business Tools Terms
            </a>
            .
          </p>
          <div className="mt-6">
            <CardGrid items={processors} />
          </div>
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">International Data Transfers</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <p className="text-black/80 leading-relaxed">
            Some of our service providers are located outside Israel and the European Economic Area, such
            as in the United States. When your data is transferred internationally, we rely on appropriate
            safeguards offered by those providers, including standard contractual clauses and recognized
            adequacy mechanisms.
          </p>
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">Data Retention</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <BulletList items={dataRetention} />
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">Your Rights</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 grid gap-6 lg:grid-cols-2">
          <div className="rounded-2xl border border-primary/10 bg-white p-6">
            <h3 className="font-head text-2xl font-semibold text-black">If you are in the EEA or UK</h3>
            <p className="mt-2 text-black/75 leading-relaxed">
              Under the GDPR, you have the right to:
            </p>
            <div className="mt-5">
              <BulletList items={gdprRights} />
            </div>
          </div>

          <div className="rounded-2xl border border-primary/10 bg-white p-6">
            <h3 className="font-head text-2xl font-semibold text-black">If you are in Israel</h3>
            <div className="mt-2 space-y-4 text-black/75 leading-relaxed">
              <p>
                Under Israel&apos;s Privacy Protection Law, you have the right to review the personal data
                we hold about you in our database and to request that we correct or update it.
              </p>
              <p>
                To exercise any of these rights, email us at{' '}
                <a
                  href="mailto:keremliving@gmail.com"
                  className="font-semibold text-primary underline underline-offset-4 transition-colors hover:text-primary-light"
                >
                  keremliving@gmail.com
                </a>
                . We will respond within the time required by applicable law.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">Data Security</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <p className="text-black/80 leading-relaxed">
            We take reasonable technical and organizational measures to protect your personal data, and we
            rely on reputable service providers to store and process it securely. However, no method of
            transmission over the internet or electronic storage is completely secure, and we cannot
            guarantee absolute security.
          </p>
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">Children&apos;s Privacy</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <p className="text-black/80 leading-relaxed">
            The website is intended for adults. We do not knowingly collect personal data from children
            under the age of 16. If you believe a child has provided us with personal data, please contact
            us and we will delete it.
          </p>
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">Third-Party Links</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <p className="text-black/80 leading-relaxed">
            Our website links to external services such as Airbnb, WhatsApp, Instagram, LinkedIn, and
            Facebook. We are not responsible for the privacy practices of those services, and we encourage
            you to review their own privacy policies.
          </p>
        </div>
      </section>

      <section className="mb-10" data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">Changes to This Policy</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <p className="text-black/80 leading-relaxed">
            We may update this policy from time to time to reflect changes in our practices or for legal
            reasons. When we do, we will revise the &ldquo;Last updated&rdquo; date at the top of this page.
          </p>
        </div>
      </section>

      <section data-animate="fade-up">
        <h2 className="font-head text-3xl font-bold text-black">Contact Us</h2>
        <div className="mt-3 h-px w-full bg-gradient-to-r from-secondary to-transparent"></div>

        <div className="mt-8 rounded-2xl border border-primary/10 bg-white p-6 md:p-8">
          <div className="rounded-2xl border border-secondary/20 bg-cream p-6">
            <h3 className="font-head text-2xl font-semibold text-black">Or Hakerem</h3>
            <address className="mt-4 not-italic space-y-2 text-black/80 leading-relaxed">
              <p>35 Hakovshim Street, Tel Aviv, Israel</p>
              <p>
                Email:{' '}
                <a
                  href="mailto:keremliving@gmail.com"
                  className="font-semibold text-primary underline underline-offset-4 transition-colors hover:text-primary-light"
                >
                  keremliving@gmail.com
                </a>
              </p>
              <p dir="ltr">
                Phone:{' '}
                <a href="tel:+972585778891" className="font-semibold text-primary hover:text-primary-light">
                  +972 58 577 8891
                </a>{' '}
                (IL) ·{' '}
                <a href="tel:+33651179925" className="font-semibold text-primary hover:text-primary-light">
                  +33 6 51 17 99 25
                </a>{' '}
                (FR)
              </p>
            </address>
          </div>

          <p className="mt-6 text-black/80 leading-relaxed">
            See also our{' '}
            <Link
              href={termsHref}
              className="font-semibold text-primary underline underline-offset-4 transition-colors hover:text-primary-light"
            >
              Terms &amp; Conditions
            </Link>{' '}
            and{' '}
            <Link
              href={cancellationHref}
              className="font-semibold text-primary underline underline-offset-4 transition-colors hover:text-primary-light"
            >
              Cancellation &amp; Refund Policy
            </Link>
            .
          </p>
        </div>
      </section>
    </>
  );
}
